[package]
name = "ferrocat"
version = "1.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Rust-first gettext and ICU toolkit for PO parsing, catalog updates, and MessageFormat parsing."
documentation = "https://docs.rs/ferrocat"
readme = "README.md"
keywords = ["ferrocat", "gettext", "po", "icu", "i18n"]
categories = ["internationalization", "localization", "parser-implementations"]

[lib]
path = "src/lib.rs"

[features]
default = ["full"]
full = ["catalog", "serde"]
catalog = ["ferrocat-po/catalog", "ferrocat-icu/serde"]
compile = ["catalog", "ferrocat-po/compile"]
mt = ["catalog", "ferrocat-po/mt"]
ndjson = ["catalog", "ferrocat-po/ndjson"]
plurals = ["catalog", "ferrocat-po/plurals"]
serde = ["ferrocat-po/serde", "ferrocat-icu/serde"]

[dependencies]
ferrocat-icu = { version = "1.1.0", path = "../ferrocat-icu", default-features = false }
ferrocat-po = { version = "1.1.0", path = "../ferrocat-po", default-features = false }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
