import { getEslintConfig } from "eslint-config-setup";

// React Router site plus the Node-side config files (vite, react-router, Ardo).
const config = await getEslintConfig({ react: true, node: true, oxlint: true });

config.unshift({
  ignores: [
    "**/dist/**",
    "build/**",
    ".react-router/**",
    "coverage/**",
    "node_modules/**",
    "pnpm-lock.yaml",
    "**/*.json",
    "**/*.md",
    // Generated by Ardo, never hand-edited (see AGENTS.md).
    "app/routes.ts",
    "app/routes/api-reference/**",
  ],
});

// Deliberate overrides on top of the org config.
config.push(
  {
    // Route modules are one flat composition of the site's sections, and they
    // export `meta`, `handle` and loaders next to the component because React
    // Router requires them in the same module. Splitting either apart to satisfy
    // a line budget would hide the page structure the design is reviewed against.
    files: ["app/**/*.tsx"],
    rules: {
      complexity: "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // The marquee renders the project list twice so the loop is seamless, so
    // the array index is what separates the visible copy from its aria-hidden
    // clone; the project name alone is not unique in that track.
    files: ["app/routes/home.tsx"],
    rules: { "react/no-array-index-key": "off" },
  },
  {
    // React Router owns this signature.
    files: ["app/entry.server.tsx"],
    rules: { "max-params": "off" },
  },
);

export default config;
