import { getOxlintConfig } from "eslint-config-setup";
import { defineConfig, type OxlintConfig } from "oxlint";

// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion -- getOxlintConfig() is not yet typed against oxlint's own OxlintConfig
const config = getOxlintConfig({ react: true, node: true }) as OxlintConfig;

config.ignorePatterns = [
  "**/dist/**",
  "build/**",
  ".react-router/**",
  "coverage/**",
  "node_modules/**",
  // Generated by Ardo, never hand-edited (see AGENTS.md).
  "app/routes.ts",
  "app/routes/api-reference/**",
];

// Same deliberate overrides as eslint.config.ts, see the comments there.
config.overrides = [
  ...(config.overrides ?? []),
  {
    files: ["app/**/*.tsx"],
    rules: {
      complexity: "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "react/only-export-components": "off",
    },
  },
  {
    // See eslint.config.ts for why the marquee keys carry the array index.
    files: ["app/routes/home.tsx"],
    rules: { "react/no-array-index-key": "off" },
  },
  {
    files: ["app/entry.server.tsx"],
    rules: { "max-params": "off" },
  },
];

export default defineConfig(config);
